version: 0.2
phases:
  install:
    commands:
      - pip install requests
      - pip install requests-aws4auth
      - aws cloudformation package --template-file template.yaml --s3-bucket lambda-voice-album --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
    - template.yaml
