AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Build template 
Resources:
  photoBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: a3-b2-jars-cftest
  LF1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::039880994656:role/service-role/a3-LF1-role-d4lue1zz
      Runtime: python3.8
      FunctionName: index-photos-cftest
      MemorySize: 128
      Timeout: 30
      CodeUri: ./lambdas/Lambda1
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref photoBucket
            Events: s3:ObjectCreated:*
  LF2:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::039880994656:role/service-role/a3-Lf2-role-q2zeugw1
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      FunctionName: search-photos-cftest
      MemorySize: 128
      Timeout: 30
      CodeUri: ./lambdas/Lambda2